USE [master]
GO

/****** Object:  Database [bdOnTime]    Script Date: 21/06/2014 03:04:41 p.m. ******/
DROP DATABASE [bdOnTime]
GO

/****** Object:  Database [bdOnTime]    Script Date: 21/06/2014 03:04:41 p.m. ******/
CREATE DATABASE [bdOnTime]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'bdOnTime', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\bdOnTime.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'bdOnTime_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\bdOnTime_log.ldf' , SIZE = 1536KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [bdOnTime] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [bdOnTime].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [bdOnTime] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [bdOnTime] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [bdOnTime] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [bdOnTime] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [bdOnTime] SET ARITHABORT OFF 
GO

ALTER DATABASE [bdOnTime] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [bdOnTime] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [bdOnTime] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [bdOnTime] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [bdOnTime] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [bdOnTime] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [bdOnTime] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [bdOnTime] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [bdOnTime] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [bdOnTime] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [bdOnTime] SET  DISABLE_BROKER 
GO

ALTER DATABASE [bdOnTime] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [bdOnTime] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [bdOnTime] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [bdOnTime] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [bdOnTime] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [bdOnTime] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [bdOnTime] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [bdOnTime] SET RECOVERY FULL 
GO

ALTER DATABASE [bdOnTime] SET  MULTI_USER 
GO

ALTER DATABASE [bdOnTime] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [bdOnTime] SET DB_CHAINING OFF 
GO

ALTER DATABASE [bdOnTime] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [bdOnTime] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [bdOnTime] SET  READ_WRITE 
GO

